id: P003099
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:40:16.341995
source_metadata:
  id: bdr:W8LS19186
  title: ཚེ་དབང་བརྒྱ་རྩ།མན་ངག་ཀུན་ཀྱི་སྙིང་བསྡུས། །རྡོ་རིང་མཛེས་བྱེད།
  author: ''
  volumes:
    4938acdaab8a4f9caefc3b50ddd6dfa1:
      image_group_id: I8LS19188
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
