id: P003099
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19186
  title: ཚེ་དབང་བརྒྱ་རྩ།མན་ངག་ཀུན་ཀྱི་སྙིང་བསྡུས། །རྡོ་རིང་མཛེས་བྱེད།
  author: ''
  volumes:
    4938acdaab8a4f9caefc3b50ddd6dfa1:
      image_group_id: I8LS19188
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
